### ISSUE TITLE
login form id and name are not the same

### ISSUE THREAD

**Issue by torvista** [zencart/zc-v1-series#179]
templates/tpl_login_default.php

<?php echo zen_draw_form('login', zen_href_link(FILENAME_LOGIN, 'action=process' . (isset($_GET['gv_no']) ? '&gv_no=' . $_GET['gv_no'] : ''), 'SSL'), 'post', 'id="loginForm"'); ?>

I understand the name and id should be the same.

**Comment by scottcwilson** [comment]
As far as I can see, the areas on the catalog side with this issue are listed below. 
However, I am not convinced that this is truly an issue - the W3C validator does not find any problems with the login page (http://www.w3.org/). 
I agree with @texdc that "name" is superfluous, but I don't think this warrants a change and would recommend closing this issue. 

./tpl_login_default.php:<?php echo zen_draw_form('login', zen_href_link(FILENAME_LOGIN, 'action=process' . (isset($_GET['gv_no']) ? '&gv_no=' . $_GET['gv_no'] : ''), 'SSL'), 'post', 'id="loginForm"'); ?>
./tpl_login_default.php:<?php echo zen_draw_form('login', zen_href_link(FILENAME_LOGIN, 'action=process' . (isset($_GET['gv_no']) ? '&gv_no=' . $_GET['gv_no'] : ''), 'SSL'), 'post', 'id="loginForm"'); ?>
./tpl_login_default.php:<?php echo zen_draw_form('create_account', zen_href_link(FILENAME_CREATE_ACCOUNT, (isset($_GET['gv_no']) ? '&gv_no=' . $_GET['gv_no'] : ''), 'SSL'), 'post', 'onsubmit="return check_form(create_account);" id="createAccountForm"') . zen_draw_hidden_field('action', 'process') . zen_draw_hidden_field('email_pref_html', 'email_format'); ?>

**Comment by scottcwilson** [comment]
Can we close this issue?

**Comment by zcwilt** [comment]
I'm happy to close, also given that templates will get a refresh in 1.6.
