### ISSUE TITLE
Add hooks for external "forum" systems

### ISSUE THREAD

**Issue by drbyte** [zencart/zc-v1-series#272]
- add hooks to make @lat9's BB plugin to only use notifier hooks (instead of touching any core files)
- drop built-in phpBB integration, in favor of community-managed BB integrations (phpBB, Discourse, etc)

**Comment by DivaVocals** [comment]
FANTASTIC!!!

**Comment by lat9** [comment]
I hate to be a pain, coming late to the party, but what about the password_forgotten processing?  In the current plugin, if a customer clicks the "Password Forgotten" link and receives a temporary password, that same temporary password is applied to their BB account, if present.

**Comment by drbyte** [comment]
The code changes were more based on extracting out the phpBB code, not specifically around the plugin's features.

That said, I've submitted another PR #371 to add the functionality requested.
