### ISSUE TITLE
Plugin Support Not working

### ISSUE THREAD

**Issue by bislewl** [zencart/zc-v1-series#281]
For certain plugins:
Example: http://www.zen-cart.com/downloads.php?do=file&id=1781
Are not returning the json
https://www.zen-cart.com/downloads.php?do=versioncheck&id=1781

Which is causing:
PHP Warning:  in_array() expects parameter 2 to be array, null given in /home/andeza200/public_html/includes/functions/plugin_support.php on line 42

See:
https://github.com/zencart/zc-v1-series/blob/v160/includes/functions/plugin_support.php#L42

**Comment by drbyte** [comment]
The JSON output has been fixed to now return the latest approved version when something is still "pending", instead of returning empty results.

**Comment by bislewl** [comment]
Should there be some "fail safe" if it can not connect to zen-cart.com?
