### ISSUE TITLE
Refactoring QueryFactory.

### ISSUE THREAD

**Issue by zcwilt** [zencart/zc-v1-series#295]
Based on comment 
https://github.com/zencart/zc-v1-series/pull/292#issuecomment-74154170
and elsewhere, regarding problems with the queryFactory interface, the fact that it addresses multiple responsibilities and uses internal methods to manage errors (rather than exceptions) and also still doesn't support PDO.

We have 3 options here.

1. Do Nothing !
2. Some minor refactoring of `queryFactory` to use exceptions rather than the error methods that currently exist
3. Use a proper PDO based SQL layer (e.g. aura.sql)

Option 1
-
 isn't really an option at all so lets ignore that :) 

Option 2
-
 while it may seem that it is a simple solution does have some drawbacks. 

i.e. 
- It doesn't address the PDO question.

- any changes to method signatures/api could possibly mean a lot of refactoring elsewhere.
- It doesn't address testability (except maybe for the refactored code)

Option 3 
-
while it may seem as it too would need wholesale refactoring elsewhere, this isn;t necessarily the case.

If the connection class from whatever package we use its created as well as the default `queryFactory` connection then we could do iterative refactoring elsewhere, and deprecate the `queryFactory` at some later date. 

It should be noted as well...
-
The work I am doing on `listingBoxes` and `Admin LEAD pages` cover off a large proportion of the SQL used in both admin and catalog. Given I'm currently refactoring both those packages, then an extra bit of refactoring to use a new SQL layer could be done, and would in fact make those packages much cleaner.

One big downside of using a new SQL layer would be the effect on current contributions. This however is mitigated by the fact that we still would have the `queryFactory` connection available until deprecated.

**Comment by texdc** [comment]
I support `PDO`, but before we do anything, we need a common interface based on the current (legacy) api.  (Always program to an interface, not the implementation.)  This will assist the transition of existing contributions - I'm guessing everything will switch from `global $db` to injecting the connection from the application container:  `$appContainer->get('data.connection.default')`.  It will also allow the use of other libraries, like `Aura.Sql` or `DBAL`, etc.  Some of the methods can be designated as `@deprecated` before actually removing them in a subsequent version.

Your work on `ListingBoxes` and `LEAD` should not include refactoring `queryFactory` - that's out of scope.  The current work on those components is suffering from scope creep enough.  Stay tightly focused on very small changes/additions/improvements.

So, the refactoring should be targeted into specific steps (PRs/features):
 - [ ] Deprecate error handling and view-related code
 - [ ] Convert to PDO
 - [ ] Add an adapter layer for external libraries
 - [ ] ...
 - [ ] Profit!

Not all of the above need to be tagged for `1.6` as long as we have a roadmap in place (this is why having `develop` and `master` branches is so helpful).  Code should live under the `ZenCart\Platform\Data` namespace.  Last but not least, and it goes without saying that with a legacy codebase this fragile, changes to the data layer will have major ripple effects throughout the application and must be made lightly.

**Comment by drbyte** [comment]
> Option 1 isn't really an option at all so lets ignore that :)

While I completely understand (and agree with) why you said that, I submit that Option 1 is indeed still an option. There's an established install base that needs to be remembered here.

I may take some flack for saying this ... but ... while "doing nothing" leaves us stuck with some of the SRP and other issues, the code is still fully functional and allows focusing on other areas of code that do require more work to accommodate other more pressing requirements.

I have no problem with having both `Aura` and `queryFactory` capability coexisting in the code for the v1.6.x series, and properly deprecate `queryFactory` in 1.7.0, as I think that's a fairly acceptable timeline for allowing third-party contributors to get up to speed with the new API.

**Comment by texdc** [comment]
I don't think you understand the concept of deprecation.  It means the function or method is still there, but it forwards the call to new functionality or throws an exception warning devs to use the new functionality.  Therefore, deprecating the view code from `queryFactory` is still viable for a `v1.6.x` release and does not need to be put off.

Brittle systems will be brittle.  Making them stable requires BC breaks.  Perpetuating a brittle state is irresponsible.

Tagging a `v1.6-alpha` release with the list of known BC breaks is a very responsible thing to do as it provides contributors the opportunity to 'get up to speed' and provide feedback.  `v1.6-beta` would be the last-call for input before the final `v1.6` version is released 'ready for production'.  Proper release management eliminates using BC breaks as an excuse for keeping the code in the dark ages.

**Comment by drbyte** [comment]
You are correct, but you knew that already.

Also it's important to not lose sight of the fact that BC issues aren't just for contributors, but also for the hundreds of thousands of end users, who don't "provide feedback" or participate in any "last-call for input" until they're trying to upgrade.

**Comment by lhungil** [comment]
In order to provide the greatest amount of compatibility with different hosting providers, I would be against supporting any one specific database driver. What if a host only supports PDO or MYSQL, not both (I know it is not likely)? What if another database is desired in the future?

We need to use (or create) interfaces and allow end users to "drop" in a driver (based on installed modules / support in a hosting environment). In particular QueryFactory, QueryResult, QueryCache, and Sniffer need to be refactored.
