### ISSUE TITLE
All free items - checkout confirmation page broken 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#318]
I was running a test with a free item and $2.50 shipping and I noticed that the checkout confirmation page was missing the confirm order button.  Sure enough, in tpl_checkout_confirmation_default.php, line 48, the display of this button is blocked if the cart total is 0. 

  if ($_SESSION['cart']->show_total() != 0) {  ?>

Removing this line (and the matching brace at the bottom of the file) fixes the issue and seems innocuous - thoughts?

**Comment by ajeh** [comment]
Good catch. 

Now I am trying to think why was that IF was added to begin with as it surely had a purpose.

**Comment by ajeh** [comment]
Had a thought, did that come with the original COWOA? I am thinking that it is a current bug with COWOA that has been brought up from time to time.

**Comment by scottcwilson** [comment]
I am set up to run a testcase if you wish - do you want me to try to COWOA with this cart?

**Comment by ajeh** [comment]
I found the bug with my fix, that matches your suggestion:
http://www.zen-cart.com/showthread.php?209975-How-can-I-setup-a-free-download

**Comment by drbyte** [comment]
Ya, the link from there goes to this discussion which confirms same: http://www.zen-cart.com/showthread.php?213979-problem-with-upgrade-from-v151-to-v153-help-please&p=1263454#post1263454

**Comment by scottcwilson** [comment]
Thank you  - just created PR.

**Comment by ajeh** [comment]
:+1:
