### ISSUE TITLE
Checker request

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#328]
Can we have the post checkin verification steps include running "php -l" on all files in the PR?  This would prevent errors such as that fixed in #324 (sorry and thanks Linda!).

**Comment by zcwilt** [comment]
Scrutinizer should pick up these problems. Unfortunately we removed the template directory from the list of directories that scrutinizer looks at. This was done to speed up scrutinizer.
Should we add it back ?

**Comment by scottcwilson** [comment]
I feel like a dope - I made that change at the very last minute just to
clean up the file and removed the unused code, and didn't retest.  Just a
suggestion.

**Comment by drbyte** [comment]
We're equally at fault for not catching it before we merged it. ;)

**Comment by scottcwilson** [comment]
Wilt, would it be possible to scrutinize *only* the template files which have changed recently?  So you'd get the best of both worlds?

**Comment by zcwilt** [comment]
Can't say that adding back the templates directory added much extra processing time, as it's very dependant on the change request and how stressed scrutinizer is at the time.
