### ISSUE TITLE
Question on work item "Template - multi-tier ... parent, child, grandchild ?"

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#340]
Would it be satisfactory to add *one* more level to the template lookup: 
- check template defined in admin->tools->template selection
- (new) check backup template (perhaps defined in same place, or perhaps statically named).
- use default file (template default or base directory for a languages file).

**Comment by Spike00** [comment]
I used exactly this solution to manage mobile template

**Comment by scottcwilson** [comment]
Thank you @Spike00 - did you use a variable name (like the current template) or did you use a fixed name?  I am tending towards a fixed name (perhaps "common"). I think this would work nicely for the Defines Page Editor (for example), where the order of search could be: 

common -> current template -> base directory (includes/languages/CURRENT_LANGUAGE/html_includes.) 

Anyone else?

**Comment by Spike00** [comment]
I wrote this as if I would release it as a plugin some day, so I thought of possible conflicts with template names and decided to use a define (so a variable name) defined in a file in extra_configures, to easy fix possible conflicts.
Introducing this feature at core distribution, would not require to have the name variable, but I don't really see the reason not to.

define('ZW_MOBILE_DIR', 'mobile');

Then 2 examples of functions regarding module and template (I didn't check if the code is the same for 1.5.4,  I made this thing on a super/ultra/hyper modified version of (an ancient) Zen)

  function zen_get_module_directory($check_file, $dir_only = 'false') {
	global $template_dir;
	$zv_filename = $check_file;
	if (!strstr($zv_filename, '.php')) $zv_filename .= '.php';
// ZW MOBILE - Start
	if (file_exists(DIR_WS_MODULES . $template_dir . '/' . ZW_MOBILE_DIR . '/' . $zv_filename)) {
	  $template_dir_select = $template_dir . '/' . ZW_MOBILE_DIR . '/';
	} else {
// ZW MOBILE - End
// Would be better to use an elseif, but this way I may simply add code without touching the existing core code
		if (file_exists(DIR_WS_MODULES . $template_dir . '/' . $zv_filename)) {
		  $template_dir_select = $template_dir . '/';
		} else {
		  $template_dir_select = '';
		}
// ZW MOBILE - Start
	}
// ZW MOBILE - End
	if ($dir_only == 'true') {
	  return $template_dir_select;
	} else {
	  return $template_dir_select . $zv_filename;
	}
  }

  function get_template_dir($template_code, $current_template, $current_page, $template_dir='', $debug=false) {
    if ($this->file_exists($current_template . $current_page, $template_code)) {
      return $current_template . $current_page . '/';
    } elseif ($this->file_exists(DIR_WS_TEMPLATES . 'template_default/' . $current_page, preg_replace('{/}', '', $template_code), $debug)) {
      return DIR_WS_TEMPLATES . 'template_default/' . $current_page;
      // ZW MOBILE - Start
    } elseif ((ZW_is_mobile()) && ($this->file_exists($current_template . ZW_MOBILE_DIR . '/' . $template_dir, preg_replace('{/}', '', $template_code), $debug))) {
      return $current_template . ZW_MOBILE_DIR . '/' . $template_dir;
      // ZW MOBILE - End
    } elseif ($this->file_exists($current_template . $template_dir, preg_replace('{/}', '', $template_code), $debug)) {
      return $current_template . $template_dir;
    } else {
      return DIR_WS_TEMPLATES . 'template_default/' . $template_dir;
      //        return $current_template . $template_dir;
    }
  }

**Comment by Spike00** [comment]
Still in development. The template function is working, the module one not, after I wrote the comment, reading it, I found errors, in effect I'm not already using it.

**Comment by scottcwilson** [comment]
PR submitted with a design of having a directory called "shared" which is searched first.  (Then your_template, then template_default).

**Comment by scottcwilson** [comment]
Should we close this issue?

**Comment by drbyte** [comment]
I think so.
Closed.
