### ISSUE TITLE
fresh install and getting a blank page

### ISSUE THREAD

**Issue by lukeengland** [zencart/zc-v1-series#452]
recently install v1.6 as a demo and getting blank catalogue and admin

http://www.lukeengland.com/cartdemos/zencartv1-6/

http://www.lukeengland.com/cartdemos/zencartv1-6/thiNk-HHC-Scoop

installed with no errors

**Comment by zcwilt** [comment]
Do you have any entries in your logs folder.

**Comment by zcwilt** [comment]
I guess also this may be a php version problem. What php version are you using.

**Comment by lukeengland** [comment]
There isn't any files in logs I'm going to do a re-install now

Php version is 5.5

**Comment by lukeengland** [comment]
i have checked all the logs with no error still having this http 500 error

**Comment by lukeengland** [comment]
I have just notice these two errors in my log
---------------
Jun 26 2015 14:57 -- checkInitialSession
FAILED
(
    [sessionName] => zenInstallerId
)

Jun 26 2015 14:58 -- checkHttpsRequest
FAILED

**Comment by zcwilt** [comment]
Are you checking the logs folder within the install.
e.g. ...cartdemos/zencartv1-6/logs/
Is that log folder writeable.

**Comment by lukeengland** [comment]
new links 

http://www.lukeengland.com/cartdemos/zencartv16/

http://www.lukeengland.com/cartdemos/zencartv16/plumS-vQy-stIff

**Comment by zcwilt** [comment]
Neither of those errors should be fatal, when accessing admin/catalog

It's a while since I did a clean install (as opposed to just a git update)
I'll test again, and see what happens.

**Comment by zcwilt** [comment]
k. yes there is a problem with the zip download

**Comment by zcwilt** [comment]
For some reason it's not pulling in the Aura/Web/WebFactory which is used to handle http requests.
will try to debug/fix
Sorry :(

**Comment by lukeengland** [comment]
few thought I was going mad

**Comment by zcwilt** [comment]
do you have ssh access to your server ??

**Comment by drbyte** [comment]
How much do you understand "git"?

If you do a `git clone` of the v160 branch, it should get the Aura stuff properly. 

(This is because the Aura package is "linked" as a submodule, instead of putting all their code into our ZC repo here. The final release would have it all packaged as one zip, but the github downloads don't auto-expand-and-include the submodule stuff)

**Comment by lukeengland** [comment]
brilliant guys all working now

**Comment by bcsteeve** [comment]
Just trying this and getting the same blank pages.  I didn't do the git command above at first, so I figured that was it... but then I did (and it did d/l more than before) but still no love!  Just blank both store and admin.

It is certainly the same issue, but drbyte's git clone command didn't resolve it for me.  This is the error:

    [30-Jun-2015 10:57:13 Europe/Paris] PHP Fatal error:  Class 'Aura\Web\WebFactory' not found in C:\wamp\www\shop16\includes\library\zencart\Request\src\Request.php on line 39

**Comment by bcsteeve** [comment]
Found some advice on the forum.

    "git submodule init" and "git submodule update"

That worked.

**Comment by lukeengland** [comment]
It took a bit of understanding of git for me but it works fine now 

Luke
