### ISSUE TITLE
Setup Wizard doesn't let me choose non-American zones

### ISSUE THREAD

**Issue by bcsteeve** [zencart/zc-v1-series#455]
I was going to report some nit-picky thing as I came across it, but then I don't recall you asking for advice :)  So I figured I'd ask.

I'll report the nit-picky thing so you have some reference:

After installing, you're taken to Initial Setup Wizard where you better be an American or else you can't choose a valid Store Zone.  At very least, "other" or "none" or "define in XYZ section" should be there.

So I chose "Alabama" then went into Configuration -> My Store and edited the zone.  At that point, it showed me Alabama as the default, and then all Canadian provinces as my other choices.

**Comment by Zen4All** [comment]
:laughing: I was about to report the same thing. The solution is already present in the store front when creating an account, so it should be pretty simple to copy that.
If the zc team has no objection, I'll be happy to take a look at it

**Comment by drbyte** [comment]
Try it out with v160 first. You'll see that the "interview" about zones etc is relocated to the "admin", and is no longer part of zc_install.  So, all zone options should be present there.  (The page admittedly still needs a bit of styling tweaking.)

Try it out and lemme know if that's what you were referring to.

**Comment by Zen4All** [comment]
Sorry I now see it says 1.5.4, but I meant 1.6.0. And I think bcsteeve did to

**Comment by drbyte** [comment]
Oh, evidently I misread it. 

It's been awhile since I even looked at that part, but I thought it fully integrated all zone possibilities in the pulldowns. 

Will have to investigate.

**Comment by bcsteeve** [comment]
Yeah, I definitely meant 1.60 and no it didn't integrate all zones, just US one.

It isn't a big deal, but it is confusing unless the person at the very least knows they can adjust it later.  Unless it is needed for something (and evidently it isn't since I can't choose it correctly at setup) then I'd suggest just removing it during zc_install rather than giving yourself more work.

**Comment by zcwilt** [comment]
@Zen4All I'm happy if you want to take a look at this. 
Will assign you to the issue.

**Comment by Zen4All** [comment]
:+1:

**Comment by zcwilt** [comment]
I took a look at the code and it gets a bit complex

There is code to fire a change on the zones when the country changes. However to javascript is using old jquery validator (rather than Foundation validation) code, that is no longer included. So we get a jscript error, which stops the on change working.

However removing the old validator code, still doesn't help as the ajax call then isn't passing the securityToken correctly, which generates another jscript error.

**Comment by bcsteeve** [comment]
really, consider just ditching it at that stage.  You already have it (working) in the Initial Setup Wizard post-install.

Frankly, that's one thing I always found annoying about ZC.  Invariably, every time I have to install I end up installing fresh probably 5 to 10 times in the first day.  Why?  Various reasons.  I screw up, I want to change something.. it always seems easier to fresh install.  But EVERY bloody time I have to type out my name, store name, address, etc... all things that can be adjusted after.

So save yourself the work, and simply eliminate all that unnecessary data from the install procedure.  Nobody is going to keep "My Store Name" forever... they'll figure out they have to change it post-install.

**Comment by drbyte** [comment]
In v154 you can already completely skip it by just aborting zc_install at that point. Then just login to the admin directly and set things there.

Or, are you saying you're installing `v160` 5-10 times in one day?

**Comment by bcsteeve** [comment]
yes, I'm saying v160 5-10 times.  The version is irrelevant.  ZC vs other carts is irrelevant.  When installing something new, there is inevitably testing and trial and error.  I can say out of experience - because this is by no means my first kick at this particular can - that every single time I do an revamp or even just an upgrade, I end up doing a fresh install at least that number of times (sometimes in an hour).  But that's not really the point - I was just giving that as another reason (besides causing yourself unnecessary work fixing something like this).

**Comment by drbyte** [comment]
Fair. Your point is fully made. You've been heard. 

And, thanks for starting this discussion. The smaller things do matter, and sometimes certain angles aren't seen as often due to differing vantage points.

I was asking about "v160 multiple times" because it's not production-ready code, and am a little alarmed at the idea of it being used on live sites yet.

**Comment by barco57** [comment]
:anguished: after ~1000 upgrades/rebuilds I can say I have never gone through the setup process for any version of ZC that many times. I couldn't conceive of a workflow that would require it. 

I do agree that the install process could probably stand to lose the store name, address, zone questions. Leave the install process to be only about getting the application talking to the database and setting up the admin user. Leave the other questions for prompting on first login to the admin, and if dismissed to leave you alone for that admin session.

**Comment by barco57** [comment]
ok, it helps if I read EVERYTHING to see that some of this has already been moved out of the install process.....probably should try installing 1.6 myself again to re familiarize with it.

**Comment by bcsteeve** [comment]
@drbyte Ahh, concern noted.  And no, not on a live site :)  I was just checking out what was coming down the pipe.

**Comment by zcwilt** [comment]
k, The fix actually isn't too complex. 
Just to be clear here. We are talking about the post install wizard that runs first time you visit the admin, in v160

Firstly the javascript code related to  validation in tplStartWizard.php needs to removed. 
Secondly need to change the url  related to the ajax for the store_country on change function to
`url: '<?php echo zen_ajax_href_link($_GET['cmd'], "action=getZones"); ?>',`
again this is in tplStartWizard.php

Thirdly, need to add a function to includes/library/zencart/src/Controllers/admin/Index.php
```php
    public function getZonesExecute()
    {
        $this->useView = false;
        $this->response = array('html'=>'');
        if ($this->request->readPost('id'))  {
            $options = zen_get_country_zones((int)$_POST['id']);
            array_unshift($options, array('id'=>0, 'text'=>TEXT_NONE));
            $html = zen_draw_pull_down_menu('store_zone', $options, -1, 'id="store_zone"');
            $this->response = array('html'=>$html);
        }
    }
```

@Zen4All if you are still happy to have a go, then please do. If not I'll create a branch and do A PR later today.

**Comment by Zen4All** [comment]
I am still willing to have a go. I'll need a couple of days, have to finish some other work first.

**Comment by zcwilt** [comment]
@Zen4All :+1:

**Comment by zcwilt** [comment]
@bcsteeve  Just to say as well. 

if you find a bug or a workflow that isn't doing what it should, then posting that here isn't nitpicking, its contributing :) 

The only thing I will say is, please don't currently post css issues. Admin and Catalog will be getting updates here soon, and we know there are issues.

**Comment by drbyte** [comment]
> if you find a bug or a workflow that isn't doing what it should, then posting that here isn't nitpicking, its contributing :)

Agreed! :+1:
