### ISSUE TITLE
listingBox doesn't set className element

### ISSUE THREAD

**Issue by drbyte** [zencart/zc-v1-series#472]
HTML output is: `<div class="centerBoxWrapper" id="id">`

The template is trying to append a `className` element, but since className is not defined, it merely outputs `id="id"` instead of `id="idSomeClassName"`

**Comment by zcwilt** [comment]
I guess as well, that `className` is not the correct naming. 
Should really be `cssIdName`

**Comment by zcwilt** [comment]
Hmm. that might not be the best name either
if you look at tpl_listing_box_columnar.php
I do 
````html
    <div class="centerBoxWrapper" id="id<?php echo $tplVars['listingBox']['className']; ?>">

and also 

    <div class="centerBoxContents<?php echo $tplVars['listingBox']['className']; ?> centeredContent back"

**Comment by drbyte** [comment]
Ya. Perhaps `cssElement` might be more generically appropriate.  I'm not seeing a need to split it into both `id` and `class` details, as for the most part it's not requiring that much specificity.
