### ISSUE TITLE
Low Order Fee issue with Coupons and GVs

### ISSUE THREAD

**Issue by ajeh** [zencart/zc-v1-series#474]
If Low Order Fee is turned on and the order is lower than the `Order Fee For Orders Under` amount, if a Discount Coupon or Gift Balance is used that covers all of the order except the Low Order Fee itself the Order can continue without a Payment Module selected.

This appears to be an old bug as it can also be reproduced in v1.3.9, v1.5, v1.5.1 and v1.5.4

**Comment by zcwilt** [comment]
Just adding this reference as a note to myself when debugging this.

https://www.zen-cart.com/showthread.php?106831-Done-v1-3-9-Problem-with-quot-credit_covers-quot
