### ISSUE TITLE
DISPLAY_PRICE_WITH_TAX_ADMIN vs DISPLAY_PRICE_WITH_TAX bug

### ISSUE THREAD

**Issue by ajeh** [zencart/zc-v1-series#489]
I agree that this is a bug in the Admin on the products_price_manager.php
https://www.zen-cart.com/showthread.php?217377-Products-Price-Manager-using-store-side-tax-definition

**Comment by scottcwilson** [comment]
Tacked on to the 1.5.4 bug list.
