### ISSUE TITLE
Undefined Specials Page sort order

### ISSUE THREAD

**Issue by ajeh** [zencart/zc-v1-series#514]
There isn't a define for the Specials Page sort order for:
PRODUCT_SPECIALS_LIST_SORT_DEFAULT

**Comment by drbyte** [comment]
Is this similarly related to #439 ?

**Comment by ajeh** [comment]
I do not believe so.

Adding to the code:
            'filters' => array(
                array(
                    'name' => 'DisplayOrderSorter',
                    'parameters' => array(
                        'defaultSortOrder' => PRODUCT_LISTING_DEFAULT_SORT_ORDER
                    )
                ),
                array(
                    'name' => 'AlphaFilter',
                    'parameters' => array()
                ),


appears to fix this but since the define for PRODUCT_LISTING_DEFAULT_SORT_ORDER needs redefining to offer the right format for selecting a sort order, I am not sure the preferred way to address this.

I lean towards using the same method as Featured Listing, New Listing, ALL Listing.

This also points out the lack of the define for Specials Page PRODUCT_SPECIALS_LIST_SORT_DEFAULT

Product Listing has its own section in Configuration ... Product Listing ... it should just need a new setting of choices.

Specials Page does not have a gang of settings so that might need to be put in either Layout Settings or something.
