### ISSUE TITLE
Terms and Conditions checked not checked issue

### ISSUE THREAD

**Issue by ajeh** [zencart/zc-v1-series#535]
When on the checkout_payment if the Terms and Conditions is checked but the payment module is not, you are given the warning to select a payment method. However the Terms and Conditions are now unchecked.

The message does not show about needing to check the Terms and Conditions the second time through. This is very aggravating especially if selecting credit card as that loses the credit card settings when you see the message to check the Terms and Conditions so you check the terms and conditions and do not notice the credit card isn't setup and now you keep having to fix things until you get it all right.

**Comment by drbyte** [comment]
The quickest end-user "fix" to this is to move the T&C segment of HTML in the template down to just above the payment choices or even below the payment choices.

Additional options include adding some javascript to alert on-page about the problem and to disable the Submit button if the T&C box isn't selected. 

In practice, most of the literature I've read about T&C litigation says there's almost no value in using a T&C box as it's often an unenforceable thing. That said, those who truly need it can use either or both of the above as quick workarounds until such time as the core template is adjusted. NOTE: No matter what happens with template_default, if a merchant has installed a custom template which has adjusted that template file already, they will need to do their own adjustments to that custom template file anyway.
