### ISSUE TITLE
Paypal EC Funding Source Errors 10422 or 10486

### ISSUE THREAD

**Issue by robryanx** [zencart/zc-v1-series#558]
I notice when PayPal returns the errors 10422 or 10486 the intended behaviour is to return the customer back to PayPal.

 if ($response['L_ERRORCODE0'] == 10422 || $response['L_ERRORCODE0'] == 10486) {
       header("HTTP/1.1 302 Object Moved");
       zen_redirect($this->ec_redirect_url);
       die();
}

I believe though that the: $this->ec_redirect_url will be blank because it is set in ec_step1 which isn't called when before_process is run.

Just wanted to check I am not missing anything here.

**Comment by drbyte** [comment]
Good thought. I'll take a deeper look at it. I'm pretty sure I tested that part specifically when making that change, but I could be wrong, and there's no harm in retesting!

NOTE: That segment of code is only in v160, not in the currently-released v154. Are you referring to actively using v160 code on a live site?

**Comment by robryanx** [comment]
Ah yes, it looks fine in v154.
I use an older version but ported these specific changes.
