### ISSUE TITLE
zcInstall*.log files trigger admin warning

### ISSUE THREAD

**Issue by lat9** [zencart/zc-v1-series#561]
I just installed v1.6.0 from the master branch (went very smoothly).  When I navigate to a non-home-page in the admin, though, I'm seeing the messages:

>Debug log file(s) discovered. Found: 4
>Error *** WARNING *** .log files may indicate problems that need to be resolved. Read the .log file(s) to resolve any errors, then delete them manually or via Tools->Store Manager.

The only files in the logs folder are the four `zcInstall*.log` files.  Shouldn't only the `myDEBUG*.log` files trigger those warnings?

**Comment by drbyte** [comment]
Or maybe we need to offer an option to delete the `zcInstall.log` files?

(There are 2 different types of zc_install log files ... one for recording normal flow, and one for actual PHP errors.)

Or, since you're "logged in to the Admin" at this point, perhaps auto-deleting the zc_install log files is appropriate at this point?

**Comment by lat9** [comment]
Are the zc_install logs that contain errors named differently?  My preference, not being a big fan of auto-deleting files, would be to alert the admin to the presence of those logs that are spontaneously generated (i.e. the admin cannot control their generation via a configuration setting) and identify errors to be investigated (e.g. `myDEBUG*.log` and the zc_install *flavor* that identifies errors).

In the current implementation, **any** file with an extension of .log is going to trigger the admin-header alert and is going to generate, IMO, a slew of zen-cart posts wondering what's wrong with their store.

The other thing I noticed in the current implementation, with the `get_logs_data` function, is that admin-page rendering is going to take **forever** in a store that has a large number of sessions (i.e. file count in the /cache directory) or a large number of files in the /logs directory, since that function is going to loop on each and every one in creating the count.

**Comment by zcwilt** [comment]
I'm wondering if we can delineate log files further using a naming convention.
e.g. 
something.error.log would be a log that gets flagged in admin
whereas 
something.info.log doesn't

**Comment by drbyte** [comment]
Perhaps, but presently none of our error-logging mechanisms indicate the "severity" of error via the filename.

**Comment by zcwilt** [comment]
Sorry. may not have explained exactly what I meant.

I don't mean that the naming convention should match the error severity. 
Only that they should denote how the error log is managed in admin.

So, the logs produced by installer would be info.logs
myDebug type logs would be error.log files.

Logs produced by say payment processors would either be info.log or error.log depending on the error reason.

does that make more sense ?

**Comment by drbyte** [comment]
The immediate issue that @lat9 was referring to is actually a bug:

When we switched to `DIR_FS_LOGS` for storing our debug logs, we missed one occurrence where `DIR_FS_SQL_CACHE` was still used. I'm submitting a PR which will cause the requisite cleanup to remove the non-critical log files, after which the false-positive @lat9 mentioned will no longer occur.
