### ISSUE TITLE
LEAD pages are missing a cacel button

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#566]
When in the admin you are adding or editing a value from for example a country. There is no cancel button to return to the previous page. I know I can just click on an item in the left menu, but I think a less experienced user might get confused.
Steps taken to:
- In the admin go to Locations / Taxes -> Countries
- Click Add country
- Now you will see only a "submit" button and no "Go back" or "Cancel"

**Comment by zcwilt** [comment]
Hi. yes this has been noted and I will get around to adding the cancel button.
Thanks
