### ISSUE TITLE
LEAD page Zone definition does not add All zones by default

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#567]
When adding a country to a tax zone definition and you do not select a zone you will get an empty value
- Go to admin -> Locations / Taxes -> Zone Definitions
- Click "Edit Sub Zones" behind a Zone Name
- Click "Add Zone Definition" on the left
- Select a country from the drop down
- Click Submit

You will now be return to the Zone Definitions list, and you can see the country added, wit no value behind it, while it should state "All Zones" (like in older ZC versions). In the database this results in a "zone_id" value of -1 instead of 0.

The reason the All Zones is not selected probably has something to do with the new filtering action when adding a country an you start typing.

I am searching for a solution, but I need to get a grip on the new lead code first, before I can start debugging

**Comment by zcwilt** [comment]
Agreed, the -1 in the database is incorrect. If you manually change the -1 to 0 then 'All Zones' shows up in the display.

**Comment by zcwilt** [comment]
The problem appears to be in the select2 handler code. 
Select2 is a javascript library we use to draw the nifty drop down selectors.
I think I have a fix for this :)

**Comment by Zen4All** [comment]
:+1:
