### ISSUE TITLE
Convert admin Reports to use new easier QueryBuilder infrastructure

### ISSUE THREAD

**Issue by drbyte** [zencart/zc-v1-series#572]
The updated admin pages (search github closed issues for `LEAD` pages) and the catalog-side ListingBoxes use a new set of QueryBuilder classes to dynamically load data which can make reporting a lot simpler than the legacy reports operate. 

The QueryBuilder and ListingBox infrastructure documentation is (partially) available at http://docs.zen-cart.com/Developer_Documentation/1.6/

Ideally this needs to start with converting `1` report (maybe a couple to better identify patterns) which will then cause a reporting template to emerge, on which all other reports will be based.

**Comment by scottcwilson** [comment]
I will do my best to do this.  I will update once I start - hopefully this month.

**Comment by scottcwilson** [comment]
Do we have any Querybuilder docs yet?  The link you gave only has ListingBox info.  Is Querybuilder ready to use?

**Comment by zcwilt** [comment]
Hi Scott.
I know you are raring to go on this one, but I think we need to have a bit more thought on the reports stuff.

While reports could share a lot of common features with the new LEAD stuff, there are other things that are needed for a general reporting infrastructure that aren't there yet. 

This would include.

* The general structure of a report page(html/css)
* The need for column ordering (something that might be useful in LEAD as well) 
* A simple way to define filter widgets (for display as listingBox already has code to manage responding to filters)

and probably a few other things.

**Comment by zcwilt** [comment]
@scottcwilson I'm going to close this for now. 
I'm currently working on  some changes to admin controller infrastructure which includes some new page types (including reports etc) 
I'm currently hitting the 80/20 rule :)  but should be able to provide an update to whats happening soon
