### ISSUE TITLE
Language define consolidation - Model Name

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#603]
If you look at a string like Model, it's defined 13 times in the catalog and 33 times in the admin.  Now some of these are different from others, but if you just consolidated (say) TEXT_PRODUCTS_MODEL, you'd get a dozen of them.  What if we promote these to the includes/languages/english file in the catalog and admin?

**Comment by drbyte** [comment]
Depends how much consolidation you're thinking of. Multiple definitions are there for ease of overriding it at a granular level. ie: product-type-specific, template-specific, site-wide

I do think there may be a bit too much flexibility there (resulting in more work when wanting to rename it to something else site-wide, or translate, etc).

Are you saying the same constant is used too often, or there are multiple constants that define the very same identical string?

**Comment by scottcwilson** [comment]
The latter.  And overriding at a granular level *can* be done by adding the define if it's truly needed - but this is an edge case that we're treating like a common practice.  If you call model "Part Number" you should only have to make this change once.
