### ISSUE TITLE
Admin Widget Styling (overall admin look and feel)

### ISSUE THREAD

**Issue by barco57** [zencart/zc-v1-series#604]
I have been playing with the widget styling, they needed some love, but I am wondering what the "Vision" is for the admin look and feel? Has there been any conversation about it?
Below is something I came up with for the widget styling that is pretty neutral.
![admin_index_widget_styling](https://cloud.githubusercontent.com/assets/1237035/10520663/fc7a3b2c-7330-11e5-920e-1c15dd68500f.png)

**Comment by drbyte** [comment]
That's a great improvement.

Is that all just done with CSS, or additional file changes needed?

Whether additional changes happen later or not, I'd be glad to include this now.

**Comment by bislewl** [comment]
:+1:

**Comment by barco57** [comment]
Just CSS Styling

If I could only figure out git, github, pull requests....LOL

**Comment by drbyte** [comment]
> Just CSS Styling

Excellent!

**Comment by drbyte** [comment]
> If I could only figure out git, github, pull requests....LOL

Well, the first step is creating an issue, so you've got that part down! :clap: 

The next is setting up your machine with git, cloning the github code, making a branch, making the code changes, and then pushing that branch to github and click the button to formally trigger the pull request. That's all described here: http://docs.zen-cart.com/Contributing/main/github_workflow

If you're stuck in there, lemme know!

**Comment by barco57** [comment]
ok, I think I figured it out and there is a pull request sitting there....Yeah me!

**Comment by drbyte** [comment]
Yay! :tada:
