### ISSUE TITLE
Admin - Styling improvements for "Setup Wizard" dialog

### ISSUE THREAD

**Issue by drbyte** [zencart/zc-v1-series#611]
TWO WAYS TO GET TO THIS SCREEN:

1. Via fresh install
a) Do a fresh install.
b) Login to Admin for the first time. (Follow the password reset prompt if it occurs.)

2. A simple reset in an existing install
a) Login to Admin
b) Go to Admin->Configuration->My Store and make either the store name or store owner be blank. Then save. 

Note the setup wizard dialog, which needs some designer love.

**Comment by jtwebsitedesign** [comment]
Need any help with this one, or is it wrapped up already?

**Comment by drbyte** [comment]
Still some open issues in #617 ... which you could collaborate with @barco57 on ... and if his time is limited you could even fork his PR and add to it and either PR it back to him or PR it back to here ... whatever you two decide.

**Comment by jtwebsitedesign** [comment]
Ok, I'm flexible with whatever @barco57 might need help on. Just let me know!

**Comment by barco57** [comment]
you can run with this if you want, I am short on time lately.

**Comment by jtwebsitedesign** [comment]
Ok, will do!
