### ISSUE TITLE
Code suggestion:  default use of html5 "email" data type

### ISSUE THREAD

**Issue by bcsteeve** [zencart/zc-v1-series#625]
This just came up as I was re-doing my template and had to edit half a dozen forms.

When a user is asked to input an email address, the data type for that field should be "email" not "text".  It is a safe change because the default "text" input type will be the fall-back if the browser doesn't support the new data type ([source](http://www.wufoo.com/html5/types/1-email.html)).

The advantage is a user with a iPhone or Android will have their keyboard default to showing @ and . symbols instead of having to switch keyboard layouts.

Simple change to make.  Anywhere we have:

zen_draw_input_field('email_address' [...]

the 4th parameter, which seems to be blank (and defaulting to "text" in the function), needs to simply be "email".

Alternatively, and perhaps better, would be some logic in the zen_draw_input_field to recognize (based on first parameter) if an email address is being specified, and then automatically apply the "email" type instead of "text" unless, of course, "text" is explicitly stated.

**Comment by drbyte** [comment]
Done in v1.5.5
