### ISSUE TITLE
Product Price Manager cannot add Quantity Discounts

### ISSUE THREAD

**Issue by ajeh** [zencart/zc-v1-series#643]
When trying to add Quantity Discounts from Product Price Manager, you can click edit, but then click Add Blanks and get a Forbidden.

Back up and see the 5 blanks. Now you can edit again and add the discounts or click update to have the discounts removed.

**Comment by drbyte** [comment]
Turns out that was an artifact of having Apache's mod_`evasive` enabled and configured with only default settings, and the add-discounts-plus-redirect-back-to-same-URL was being flagged as DoS-like activity, hence the 403 response.
