### ISSUE TITLE
warning in install upon changing admin folder (zc1.5.5)

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#668]
During the installation of Zen Cart 1.5.5 the admin folder name is automatically renamed from admin to something more obscure. This if good, but then I get the message "We did not change your admin directory automatically as it already seems to have been changed from the default.". This is not true, the installation script changed it for me.
This could confuse some users in thinking something went wrong with their installation. There should probably be some check if the original folder name was "admin" or not.
![zc_install_admin_setup](https://cloud.githubusercontent.com/assets/2766593/11680172/98e11e18-9e56-11e5-9b1b-6791c121b5bd.jpg)

**Comment by drbyte** [comment]
Fixed by #687
