### ISSUE TITLE
After initial install Zone is not updated (zc1.5.5)

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#669]
When entering the admin of Zen Cart 1.5.5 for the first time the admin is asked to fill in the store information.
In this case I filled in "Netherlands" for country. The zone drop down automatically empties, and can not be selected. All seems fine and I click "Update.
"Then I visit admin => Store, and see my country as "Netherlands", but the zone is still the default "Florida".
![initial_setup_wizard](https://cloud.githubusercontent.com/assets/2766593/11680649/057c0d1e-9e5a-11e5-88cd-4bfdd5f0eb52.jpg)

![wrong_zone](https://cloud.githubusercontent.com/assets/2766593/11680567/6ad6a274-9e59-11e5-8ecb-4b8cbb31044e.jpg)

**Comment by Zen4All** [comment]
Just noticed that in 1.6.0 this results in Zone being set to 0
![wrong_zone_zc160](https://cloud.githubusercontent.com/assets/2766593/11683608/2cf03a66-9e6c-11e5-872d-cb6214a05c08.jpg)

**Comment by drbyte** [comment]
Fixed via #696
