### ISSUE TITLE
Multiple languages create debug logs in new language

### ISSUE THREAD

**Issue by zcwilt** [zencart/zc-v1-series#67]
ISSUE-105

Add French language and when in French, any navigation in Admin generates debug log:
[21-May-2014 16:09:13 UTC] PHP Warning: htmlspecialchars(): charset `CHARSET' not supported, assuming iso-8859-1 in /v153/admin2/includes/functions/general.php on line 39
[21-May-2014 16:09:13 UTC] PHP Warning: htmlspecialchars(): charset `CHARSET' not supported, assuming iso-8859-1 in /v153/admin2/includes/functions/general.php on line 39

**Comment by drbyte** [comment]
This situation should only occur if `CHARSET` is not defined properly. 

Note: v1.6.0 moved `CHARSET` and several other locale-specific defines into the `locale.php` language file. As such, old language packs might need some changes for optimal compatibility.

**Comment by drbyte** [comment]
I believe this still needs investigation

**Comment by scottcwilson** [comment]
D-ohhh!  Can you give me repro steps and I'll give it another shot?

**Comment by zcwilt** [comment]
Currently I'm not seeing a problem, albeit I just copied/renamed the English language fiiles/folders to create a 'French' language.

**Comment by scottcwilson** [comment]
It has been several months now; I believe this issue was fixed in my original PR.  Also submitting a fix for #400.
