### ISSUE TITLE
$options_html_id returns empty string (zc 1.5.5)

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#671]
in the file "includes\templates\template_default\templates\tpl_modules_attributes.php" on line 30

    <div class="wrapperAttribsOptions" id="<?php echo $options_html_id[$i]; ?>">

$options_html_id is echoed, but it is never set. I suspect that should be done in "includes\modules\attributes.php"

**Comment by drbyte** [comment]
Fixed. https://github.com/zencart/zc-v1-series/commit/e217333bc2d34508b171f978aa9f8835a1aa32da

**Comment by Zen4All** [comment]
:+1:

**Comment by Zen4All** [comment]
:+1:
