### ISSUE TITLE
Micro code delete

### ISSUE THREAD

**Issue by Spike00** [zencart/zc-v1-series#677]
/includes/classes/db/mysql/query_factory.php

row 476 in v1.5.5 (but it affects all versions, 1.6.0 included)

https://github.com/zencart/zc-v1-series/blob/v160/includes/classes/db/mysql/query_factory.php#L488

`$bindVarTypeArray = explode(':', $bindVarType);`

This is not used, it could be deleted.

**Comment by scottcwilson** [comment]
Paulo, thanks for your suggestion to help improve the code base!
