### ISSUE TITLE
ajax.php: htmlentities recursion breaks authorize.net AIM

### ISSUE THREAD

**Issue by lat9** [zencart/zc-v1-series#678]
When the htmlentities_recurse functionality is used with a site that also uses a.net/AIM, the checkout process breaks.

The *prepareConfirmation* function of /includes/classes/ajax/zcAjaxPayment.php returns an array that includes htmlentities.  When the updated functionality is introduced in the ajax.php file, all the htmlentities are replaced, which is not expected by the jQuery that issued the prepareConfirmation request, resulting in an unwanted display of pseudo-HTML on the checkout-payment page.

Updated:  The HTML "dump" occurs on the payment, not confirmation page.

**Comment by drbyte** [comment]
I'm assuming this is on v154 that you're seeing this?  or testing on v155.

**Comment by lat9** [comment]
Yes, this is on Zen Cart v1.5.4 (sorry for the incomplete description).

**Comment by drbyte** [comment]
Okay. The published "patch" for ajax.php doesn't contain the recursive part, so I'm guessing you're using the code from v155 at https://github.com/zencart/zc-v1-series/blob/v155/ajax.php ... ?

Just clarifying to be sure we're looking at the same thing you are ;)

**Comment by lat9** [comment]
DrByte, what you said is close-to-true; the site's using the slightly-different version from my POSM plugin.  Let me grab the 1.5.5 version just to verify that I'm seeing the same issue.

**Comment by lat9** [comment]
Just validated the site in question.  Using the zc155 version of ajax.php, and choosing authorizenet_aim as the payment method, upon entering the credit-card information the checkout-payment page is redisplayed with an HTML "dump" from the prepareConfirmation function's output.

The console log shows a call to doesCollectsCardDataOnsite, returning `{"data":"1"}` and then a call to prepareConfirmation which results in the HTML dump due to the htmlentities being replaced in the HTML returned by that function.

**Comment by lat9** [comment]
It looks like a change is required to /includes/modules/pages/checkout_payment/jscript_main.php to "un-decode" those entities.

**Comment by lat9** [comment]
One question that I've not seen the answer to.  This festuch began with a change to correct the logging of `PHP Warning: Invalid UTF-8 sequence in argument in /ajax.php`.  How did this map to a solution that required converting the HTML entities?

**Comment by zcwilt** [comment]
IIRC This was the original thread
https://www.zen-cart.com/showthread.php?216691-PHP-Warning-Invalid-UTF-8-sequence-in-argument-in-ajax-php-on-line-24

**Comment by lat9** [comment]
Wilt, thanks for pulling it together!  That feeds my previous question:  Why use `htmlentities` to correct an invalid utf-8 sequence (aka encoding) issue instead of checking to see if the site's already using UTF-8 encoding and, if not, sending the data (recursively) down a `utf8-encode` processing path?

**Comment by zcwilt** [comment]
There was also this forum post as well 
https://www.zen-cart.com/showthread.php?218140-Got-a-blank-page-during-check-out-payment-with-V154

**Comment by lat9** [comment]
Yep, I saw that one too.  Unfortunately, there's not enough information to understand what the root cause of the PHP warning was.  Was the OP's site set up using a `utf-8` CHARSET or not?  What *was* that invalid data?

Given that the json_encode function requires utf8-encoded input to prevent that warning from being issued, what happens when the function's input is now properly encoded ... but on a site that's using a non-utf8 CHARSET?  How does the now-utf8-encoded data get rendered on the customer's display?

**Comment by lat9** [comment]
I've attached an update to the ajax.php (renamed to .txt so I could attach it) processing that uses utf8_encode to (er) encode the utf8 characters ... **iff** the site's not already using UTF-8 encoding (don't want to double-encode).

I still question, however, how the utf8_encoded data is going to display on a site that's using a non-utf8 encoding.

[ajax.txt](https://github.com/zencart/zc-v1-series/files/59755/ajax.txt)

**Comment by zcwilt** [comment]
Hi

Sorry for taking a while to get back on this, but there was a bug in v155 authnet that made it difficult to test your changes. 

I've incorporated your changes into current v155 code and it looks OK so far.

I guess this speaks to our review/testing process and to us responding in a somewhat knee jerk, to some posts on the internet regarding Black Friday and Zen Cart.

**Comment by lat9** [comment]
Thanks, zcwilt, for the update!

**Comment by drbyte** [comment]
I believe this is now resolved ... so closing. Feel free to re-open if I'm wrong.
