### ISSUE TITLE
product_type parameter in admin is not validated properly

### ISSUE THREAD

**Issue by zcwilt** [zencart/zc-v1-series#69]
if the GET parameter for product_type is altered to use an out of range value, the code still does the look up but returns a blank hander name. It then attempts to load product handler code based on an incorrect path.

**Comment by scottcwilson** [comment]
@zcwilt I have looked through the code and don't see anywhere that this is happening - can you give me the URL that triggered the FP?

**Comment by zcwilt** [comment]
Let me take a look again. It maybe it was fixed as part of our last PA-DSS round.

**Comment by zcwilt** [comment]
e.g.
https://zen.local/admin/index.php?cmd=product_free_shipping&page=1&product_type=5&cPath=64&pID=172&action=new_product

change the product_type parameter to 99
