### ISSUE TITLE
attribute controller errors with option names that only have no values - issue #799

### ISSUE THREAD

**Issue by mc12345678** [zencart/zc-v1-series#800]
Tested method to letting attributes controller to allow adding attributes to product when the option names assigned do not have (by design) associated values is addressed in issue #799. 

If recollection is correct this affects more than ZC 1.5.5.  I believe I have seen others in the past experience this.

Alternate non-coding solution is to add an option name that will accept an option value and then to assign an option value to that option name. On next run of the attributes controller no further error messages are displayed about the absence of option values (and still none for option names as now at least two would be in the database).

Issue would be apparent for stores that use only text attributes or file upload attributes. Similar situation would occur if some option name was created by a developer that did not use option values with the associated option name. All such conditions are addressed in the above pull request in admin/includes/functions/general.php (accessible by the admin) as well as for store front use if deemed necessary in includes/functions/functions_lookups.php.

**Comment by mc12345678** [comment]
Correction (unable to edit above at the moment based on accessing platform) file containing new code is includes/functions/functions_lookups.php.

**Comment by drbyte** [comment]
Fixed by https://github.com/zencart/zc-v1-series/pull/799
