### ISSUE TITLE
Language dropdown missing from header

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#856]
In Zen Cart 1.6 the language select drop down is missing from the header in the new LEAD pages.
It looks like the variables "admin\includes\init_includes\init_header.php" isn't used and thus not loading the variables needed for the drop down.

On further investigation the version check is also missing, which makes sense if init_header.php is not loaded.
Old style:
![original pagestyle](https://cloud.githubusercontent.com/assets/2766593/13488259/61ca62a6-e120-11e5-8127-bf8a8701cca3.jpg)

new style:
![lead page style](https://cloud.githubusercontent.com/assets/2766593/13488258/61c7e7d8-e120-11e5-8bc4-6da216f5f608.jpg)
![lead index page](https://cloud.githubusercontent.com/assets/2766593/13488260/61cae636-e120-11e5-877e-ac7f264d6548.jpg)

**Comment by zcwilt** [comment]
Thanks, will investigate
