### ISSUE TITLE
change password fields not aligned

### ISSUE THREAD

**Issue by Zen4All** [zencart/zc-v1-series#872]
When asked to change your password on "Admin Login - Password Expired", in Zen Cart 1.5.5
The fields are not aligned. The first immage is on a wide screen (1280px), and the second on a smaller screen (1024px).
![changepassword](https://cloud.githubusercontent.com/assets/2766593/13814062/275b8a86-eb85-11e5-9324-bbd38c58cb9b.jpg)
![changepassword-01](https://cloud.githubusercontent.com/assets/2766593/13814067/2a2c3152-eb85-11e5-81a2-a1625861b061.jpg)
the labels and input fields are in separate divs, which is probably causing the issue.

**Comment by drbyte** [comment]
Thanks. Fixed by #875
