### ISSUE TITLE
Suggestion: default for ACCOUNT_DOB, ACCOUNT_GENDER be false

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#915]
Most people truly don't need either of these, and additional data collection at account creation time is annoying to customers.  Defaulting them to off means people who really want or need these fields still have access to them but others don't have to remember to turn them off.

**Comment by Zen4All** [comment]
👍

**Comment by drbyte** [comment]
I'm willing to entertain a PR for this

**Comment by scottcwilson** [comment]
Very good.  Will do this week.
