### ISSUE TITLE
Suggestion: Migrate use of Font Awesome icons out of language files 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#917]
These additions in admin/includes/languages/english/orders.php make it much harder to reuse these defines in other mods such as edit orders.  Any objections to me breaking up things like 

define('ENTRY_CUSTOMER_ADDRESS', 'Customer Address:<br><i class="fa fa-2x fa-user"></i>');

into

define('ENTRY_CUSTOMER_ADDRESS', 'Customer Address:<br>');
define('ENTRY_CUSTOMER_ADDRESS_ICON', '<i class="fa fa-2x fa-user"></i>');

I would do 1.5.5a and 1.6.0 if approved.

**Comment by drbyte** [comment]
I'm not sure I like the addition of more constants just for icons. It's probably best to leave the icons in the original source code, as technically they are markup for the page. 

I'm pretty sure they were just dropped in to the language file to minimize other changes to the core files in a minor release.

**Comment by scottcwilson** [comment]
So to clarify - if I removed them from the language file and put them in the source code, you would approve the PR?  (If so, I will do.)

**Comment by drbyte** [comment]
For v160 yes. After the v155 code is fully merged (which I hope to finish later today).
